#!/usr/bin/env bash
# Update /etc/hosts

sudo sed -i 's/^127\\.0\\.0\\.1\\s\\+localhost/127.0.0.2    localhost/' "/etc/hosts"

# Add facebook.com entry

echo "8.8.8.8      facebook.com" | sudo tee -a "/etc/hosts" > /dev/null

